#!/bin/bash
# -----------------------------------------------------------------
# [Azkarate] Testing Script
#            Just prints a sting on the standard error
# -----------------------------------------------------------------

echo 'this is a test from Mikel Azkarate-askatsua'

